/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as PrintRouteImport } from './routes/print'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LearnTopicIdRouteImport } from './routes/learn.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicIdRoute = LearnTopicIdRouteImport.update({
  id: '/learn/$topicId',
  path: '/learn/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/glossary': typeof GlossaryRoute
  '/print': typeof PrintRoute
  '/quiz': typeof QuizRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/glossary': typeof GlossaryRoute
  '/print': typeof PrintRoute
  '/quiz': typeof QuizRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/glossary': typeof GlossaryRoute
  '/print': typeof PrintRoute
  '/quiz': typeof QuizRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/flashcards' | '/glossary' | '/print' | '/quiz' | '/learn/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flashcards' | '/glossary' | '/print' | '/quiz' | '/learn/$topicId'
  id:
    | '__root__'
    | '/'
    | '/flashcards'
    | '/glossary'
    | '/print'
    | '/quiz'
    | '/learn/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GlossaryRoute: typeof GlossaryRoute
  PrintRoute: typeof PrintRoute
  QuizRoute: typeof QuizRoute
  LearnTopicIdRoute: typeof LearnTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topicId': {
      id: '/learn/$topicId'
      path: '/learn/$topicId'
      fullPath: '/learn/$topicId'
      preLoaderRoute: typeof LearnTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsRoute: FlashcardsRoute,
  GlossaryRoute: GlossaryRoute,
  PrintRoute: PrintRoute,
  QuizRoute: QuizRoute,
  LearnTopicIdRoute: LearnTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
